In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv("avocado.csv")
data.head(5)

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0           0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1           1  2015-12-20          1.35      54876.98   674.28   44638.81   
2           2  2015-12-13          0.93     118220.22   794.70  109149.67   
3           3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4           4  2015-11-29          1.28      51039.60   941.48   43838.39   

     4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0   48.16     8696.87     8603.62       93.25          0.0  conventional   
1   58.33     9505.56     9408.07       97.49          0.0  conventional   
2  130.50     8145.35     8042.21      103.14          0.0  conventional   
3   72.58     5811.16     5677.40      133.76          0.0  conventional   
4   75.78     6183.95     5986.26      197.69          0.0  conventional   

   year  region  
0  2015  Albany  
1  2015  Albany  
2  2015  Albany  
3  2015  Albany  
4  2015  Albany

In [3]:
df=data[["year","Small Bags","Large Bags", "AveragePrice"]]
df

year  Small Bags  Large Bags  AveragePrice
0      2015     8603.62       93.25          1.33
1      2015     9408.07       97.49          1.35
2      2015     8042.21      103.14          0.93
3      2015     5677.40      133.76          1.08
4      2015     5986.26      197.69          1.28
...     ...         ...         ...           ...
18244  2018    13066.82      431.85          1.63
18245  2018     8940.04      324.80          1.71
18246  2018     9351.80       42.31          1.87
18247  2018    10919.54       50.00          1.93
18248  2018    11988.14       26.01          1.62

[18249 rows x 4 columns]

In [4]:
df.dtypes

year              int64
Small Bags      float64
Large Bags      float64
AveragePrice    float64
dtype: object

In [5]:
df.isna().sum()

year            0
Small Bags      0
Large Bags      0
AveragePrice    0
dtype: int64

## Prediction for SMALL BAGS & The average price

In [6]:
x=df.iloc[:,1].values
y=df.iloc[:,-1].values

In [7]:
x=x.reshape(len(x),1)
y=y.reshape(len(y),1)


## Training the Decision Tree Regression model on the whole dataset

In [8]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

DecisionTreeRegressor(random_state=0)

In [9]:
## Predicting a new result: What is the price for the 
regressor.predict([[8042.21]])


array([0.93])

In [10]:
regressor.predict([[8000]])


array([1.26])

In [11]:
regressor.predict([[18000]])


array([1.05])

## Visualization

In [ ]:
X_grid = np.arange(min(x), max(x), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))

plt.scatter(x,y, color="red")
plt.plot(X_grid, regressor.predict(X_grid), color="blue")

plt.title("Decision Tree Regression for Avocado Prices")
plt.xlabel("Price")
plt.ylabel("Avocado Small Bags")
plt.show()
